// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMKbsThP4D8BHzj9q6t3_jnMtmCXv3CtE',
    appId: '1:192595738289:web:0498687da492db8f5bec90',
    messagingSenderId: '192595738289',
    projectId: 'news-app-41a64',
    authDomain: 'news-app-41a64.firebaseapp.com',
    storageBucket: 'news-app-41a64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXF7VBk1OUPQXuMTg5kv92nMpptDWgAUk',
    appId: '1:192595738289:android:735e81998ad7f7b45bec90',
    messagingSenderId: '192595738289',
    projectId: 'news-app-41a64',
    storageBucket: 'news-app-41a64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6FnC1DzO_co2eUDg2Y7ZJNAVdNvSWQ-o',
    appId: '1:192595738289:ios:7a9971a04e512baf5bec90',
    messagingSenderId: '192595738289',
    projectId: 'news-app-41a64',
    storageBucket: 'news-app-41a64.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6FnC1DzO_co2eUDg2Y7ZJNAVdNvSWQ-o',
    appId: '1:192595738289:ios:7a9971a04e512baf5bec90',
    messagingSenderId: '192595738289',
    projectId: 'news-app-41a64',
    storageBucket: 'news-app-41a64.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMKbsThP4D8BHzj9q6t3_jnMtmCXv3CtE',
    appId: '1:192595738289:web:f0b72fd275f362fd5bec90',
    messagingSenderId: '192595738289',
    projectId: 'news-app-41a64',
    authDomain: 'news-app-41a64.firebaseapp.com',
    storageBucket: 'news-app-41a64.firebasestorage.app',
  );
}
